### ISSUE TITLE
Nutrition Framework - Fails to run some subshorcuts

### ISSUE THREAD

**Issue by kiedanski** [iffy-pi/apple-shortcuts#47]
Hi, first of all, thanks for the work on this shortcut. It looks awesome.

I have been trying it today and I can't get it to work.

I tried making a preset and searching for food. I get the oatmeal correctly from the API but when I confirm that everything is ok I get the following error:

![image](https://github.com/iffy-pi/apple-shortcuts/assets/49415614/9f9c769e-24c2-4f6b-96ec-e0e16132cb1c)

It originally showed it as a variable but I could not find the definition. I tried to change it to the shortcut name and it didn't work either. Any help?

I'm running on: iPhone 11 Pro, iOS 17.2.1

**Comment by iffy-pi** [comment]
Hi Diego, thanks for reporting this issue!
A couple of questions:
- When you are making the Preset, are you doing it by:
	- Nutrition > Saved Foods and Search > Presets > Make Preset, or
	- Nutrition > Saved Foods and Search > Search and View > Make Preset
- Could you also provide what food you searched for specifically?

**Comment by kiedanski** [comment]
Uploading nutrition_shortcut.mov…

**Comment by kiedanski** [comment]
https://github.com/iffy-pi/apple-shortcuts/assets/49415614/256b68e1-0b57-4b8d-955c-4f15d2b4dd9d

**Comment by iffy-pi** [comment]
Hi Diego,
Sorry for taking a while to get back to you. This issue occurs as a result of the numbering system you have configured on your phone:

![image](https://github.com/iffy-pi/apple-shortcuts/assets/59808927/074427f1-f98d-43ff-974b-250a93d54c77)

You use PTCD (periods for thousands, commas for decimals) (the second one), while I designed the shortcut to work in the first one (CTPD).

I do realize this limits its accessibility so I will be working within your number system to fix any issues that are occuring

**Comment by iffy-pi** [comment]
Is continuation of Issue #1 , refer to that issue for technical details on how it was fixed

**Comment by iffy-pi** [comment]
Hi Diego,
I have made the required fixes to support your numbering system. I tested it myself and it did work, however if you encounter any other bugs or issues don't hesitate to reach out.

You can download the fixes by performing a shortcut update: Run Nutrition Installer > Check For Updates. The fix is present in v4.10 and later!

Let me know if you are able to successfully install the shortcuts and if it fixes your issue!

**Comment by kiedanski** [comment]
Hi, thanks for working on this. Now I can log foods correctly. 

One lingering issue: the amount of consumed calories seems to be wrong: the health app shows only 290

![image](https://github.com/iffy-pi/apple-shortcuts/assets/49415614/e6d0d3aa-d1c7-4f76-92b6-be624ad32fb4)

Probably still related to the number format

**Comment by iffy-pi** [comment]
Yep you're right. Missed that during my checking
Since I just released the update, I pushed it out as a hotfix (#51)
You can download the fixed version here:
https://www.icloud.com/shortcuts/2199bf9d239c47569c98abc6fc838fcb

**Comment by iffy-pi** [comment]
Hi Diego, Just checking if everything is working alright?

**Comment by iffy-pi** [comment]
Haven't heard issues from user, assuming everything is fine
